[alias]
loco = "run --"
playground = "run --example playground"
meme = "shuttle resource list --name shuttle-graphql-ex --show-secrets | awk -F '┆' '!/Connection string/ && NR>2 {gsub(/^[[:space:]]+|[[:space:]]+$/, \"\", $2); if ($2) print $2}' | sed 's/│//' > cat.txt"
